server:
  port: 8080

spring:
  application:
    name: data-transport
  profiles:
    active: default
  spring:
    datasource:
      url: jdbc:mysql://datatransport.c7hdso3luiog.ap-east-1.rds.amazonaws.com:3306/data_transport
      username: root
      password: root1234
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        min-idle: 5
        max-active: 20
        initial-size: 5
        max-wait: 6000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.happy.video.pojo
  configuration:
    map-underscore-to-camel-case: true

jwt:
  expire: 60
