server:
  port: 8080

spring:
  application:
    name: data-transport
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://datatransport.c7hdso3luiog.ap-east-1.rds.amazonaws.com:3306/data_transport
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout : 30000
      idle-timeout : 600000
      max-lifetime : 1800000
      maximum-pool-size : 20
      minimum-idle : 10

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.data.transport.domain
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml

jwt:
  expire: 60
